// Pixelové postavičky 16 × 16. Každý znak je jeden pixel:
// . průhledná, K obrys, W bílá, M barva modulu, D stín, L světlo, R tvářičky.
// Postavičky modulů mají jednotný obličej: oči 1×2 px, růžové tvářičky, pusa 2 px.

import type { ModuleKey } from "./modules";

export type SpriteName =
  | ModuleKey | "star" | "trophy" | "crown" | "lock" | "heart" | "flame" | "check" | "sparkle"
  | "i-home" | "i-grid" | "i-map" | "i-user" | "i-plus" | "i-back" | "i-up" | "i-down" | "i-star" | "i-play";

export const SPRITES: Record<SpriteName, string[]> = {
  piva: [
    "................",
    "...KKK.KKKK.....",
    "..KWWWKWWWWK....",
    ".KWWWWWWWWWWK...",
    ".KLWWWWWWWWWK...",
    ".KMLWWLWWWLMK...",
    ".KLMMMMMMMMMKKK.",
    ".KLMMMMMMMMMKDDK",
    ".KLMKMMMMKMMK.DK",
    ".KLMKMMMMKMMK.DK",
    ".KMRMMKKMMRMKDDK",
    ".KMMMMMMMMMMKKK.",
    ".KDMMMMMMMMDK...",
    ".KDDDDDDDDDDK...",
    "..KKKKKKKKKK....",
    "................",
  ],
  meditace: [
    "................",
    ".....KKKKKK.....",
    "....KLLMMMMK....",
    "...KLMMMMMMMK...",
    "...KMMMMMMMMK...",
    "...KMKKMMKKMK...",
    "...KRMMMMMMRK...",
    "...KMMMKKMMMK...",
    "....KDMMMMDK....",
    "..KKKKMMMMKKKK..",
    ".KLMMMMMMMMMMMK.",
    ".KMMKMMMMMMKMMK.",
    "KMMMMMMMMMMMMMMK",
    "KDDDDDDDDDDDDDDK",
    ".KKKKKKKKKKKKKK.",
    "................",
  ],
  hlaskomat: [
    "................",
    "...KKKKKKKKKK...",
    "..KLLMMMMMMMMK..",
    ".KLMMMMMMMMMMMK.",
    ".KLMMMMMMMMMMMK.",
    ".KMMMKMMMMKMMMK.",
    ".KMMMKMMMMKMMMK.",
    ".KMMRMMKKMMRMMK.",
    ".KMMMMMKKMMMMMK.",
    ".KDMMMMMMMMMMDK.",
    "..KDDMMMMMMDDK..",
    "...KKKDDKKKKK...",
    ".....KDK........",
    "....KDK.........",
    "....KK..........",
    "................",
  ],
  trenink: [
    "................",
    ".....KKKKKK.....",
    "....KDDDDDDK....",
    "...KDK....KDK...",
    "...KDK....KDK...",
    "..KKKKKKKKKKKK..",
    ".KLLMMMMMMMMMMK.",
    "KLMMMMMMMMMMMMMK",
    "KLMMKMMMMMMKMMMK",
    "KMMMKMMMMMMKMMMK",
    "KMMRMMMKKMMMRMMK",
    "KMMMMMMMMMMMMMMK",
    "KDMMMMMMMMMMMMDK",
    ".KDDDDDDDDDDDDK.",
    "..KKKKKKKKKKKK..",
    "................",
  ],
  lide: [
    "................",
    "...KKK....KKK...",
    "..KWWLK..KLWWK..",
    "..KWKLWKKWLKWK..",
    "...KKKWWWWKKK...",
    ".KKKKKKWWKKKKKK.",
    ".KLMMMMWWMMMMMK.",
    ".KDDDDDWWDDDDDK.",
    ".KKKKKKWWKKKKKK.",
    "..KMMMMWWMMMMK..",
    "..KMKMMWWMMKMK..",
    "..KMKMMWWMMKMK..",
    "..KRMMMWWMMMRK..",
    "..KDDDDWWDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
  ],
  denik: [
    "................",
    "..KKKKKKKKKKKK..",
    "..KDKLMMMMRRMK..",
    "..KDKMMMMMRRMK..",
    "..KDKMMMMMRRMK..",
    "..KDKMMMMMKRMK..",
    "..KDKMMMMMMMMK..",
    "..KDKMKMMMKMMK..",
    "..KDKMKMMMKMMK..",
    "..KDKRMMMMMRMK..",
    "..KDKMMMKKMMMK..",
    "..KDKMMMMMMMMK..",
    "..KDKDDDDDDDDK..",
    "..KKKWWWWWWWWK..",
    "...KKKKKKKKKKK..",
    "................",
  ],
  odkazy: [
    "................",
    "....KKKKKKKK....",
    "...KLLMMMMMMK...",
    "...KLMMMMMMMK...",
    "...KMMMMMMMMK...",
    "...KMKMMMMKMK...",
    "...KMKMMMMKMK...",
    "...KRMMKKMMRK...",
    "...KMMMMMMMMK...",
    "...KMMMMMMMMK...",
    "...KDMMMMMMDK...",
    "...KDDMKKMDDK...",
    "...KDMK..KMDK...",
    "...KMK....KMK...",
    "...KK......KK...",
    "................",
  ],
  mista: [
    "................",
    ".....KKKKKK.....",
    "....KLLMMMMK....",
    "...KLMMMMMMMK...",
    "...KMMMMMMMMK...",
    "...KMKMMMMKMK...",
    "...KMKMMMMKMK...",
    "...KRMMKKMMRK...",
    "...KDMMMMMMDK...",
    "....KDMMMMDK....",
    ".....KDMMDK.....",
    "......KDDK......",
    ".......KK.......",
    "....KKKKKKKK....",
    "................",
    "................",
  ],
  filmy: [
    "................",
    ".KKKKKKKKKKKKKK.",
    ".KWKKWWKKWWKKWK.",
    ".KKWWKKWWKKWWKK.",
    ".KKKKKKKKKKKKKK.",
    ".KLMMMMMMMMMMMK.",
    ".KLMMMMMMMMMMMK.",
    ".KMMKMMMMMMKMMK.",
    ".KMMKMMMMMMKMMK.",
    ".KMRMMMKKMMMRMK.",
    ".KMMMMMMMMMMMMK.",
    ".KDDDDDDDDDDDDK.",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
    "................",
  ],
  wishlist: [
    "................",
    "................",
    "....KKKKKKKK....",
    "...KWLLMMMMDK...",
    "..KWLLMMMMMMDK..",
    ".KKKKKKKKKKKKKK.",
    ".KLMMKMMMMKMMDK.",
    "..KLMKMMMMKMDK..",
    "...KRMMKKMMRK...",
    "....KMMMMMMK....",
    ".....KMMMDK.....",
    "......KMDK......",
    ".......KK.......",
    "................",
    "................",
    "................",
  ],
  finance: [
    "................",
    ".....KKKKKK.....",
    "...KKLLMMMMKK...",
    "..KLLMMMMMMMDK..",
    ".KLMMMMMMMMMMDK.",
    ".KLMMKMMMMKMMDK.",
    ".KMMMKMMMMKMMDK.",
    ".KMMRMMKKMMRMDK.",
    ".KMMMMMMMMMMMDK.",
    ".KMMMMMMMMMMDDK.",
    "..KDMMMMMMMDDK..",
    "...KKDDDDDDKK...",
    ".....KKKKKK.....",
    "................",
    "................",
    "................",
  ],
  star: [
    ".......KK.......",
    "......KLMK......",
    "......KLMK......",
    ".....KLMMMK.....",
    "KKKKKKLMMMKKKKKK",
    "KLLLLLLMMMMMMMDK",
    ".KLMMMMMMMMMMDK.",
    "..KMMMMMMMMMDK..",
    "...KMMMMMMMDK...",
    "...KMMMMMMMDK...",
    "..KMMMMKKMMMDK..",
    "..KMMMK..KMMDK..",
    ".KMMDK....KMDDK.",
    ".KKKK......KKKK.",
    "................",
    "................",
  ],
  trophy: [
    "................",
    "...KKKKKKKKKK...",
    ".KKKMMMMMMLMKKK.",
    "KM.KMMMMMMLMK.MK",
    "KM.KMMMMMMMMK.MK",
    ".KKKMMMMMMMMKKK.",
    "...KMMMMMMMMK...",
    "....KMMMMMMK....",
    ".....KKMMKK.....",
    "......KMMK......",
    "......KMMK......",
    "....KKKKKKKK....",
    "....KDDDDDDK....",
    "....KKKKKKKK....",
    "................",
    "................",
  ],
  crown: [
    "................",
    "................",
    "................",
    "..K....K....K...",
    ".KMK..KMK..KMK..",
    ".KMMK.KMK.KMMK..",
    ".KMMMKMMMKMMMK..",
    ".KMMMMMMMMMMMK..",
    ".KMRMMMRMMMRMK..",
    ".KMMMMMMMMMMMK..",
    ".KKKKKKKKKKKKK..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  lock: [
    "................",
    "................",
    ".....KKKKKK.....",
    "....KK....KK....",
    "....K......K....",
    "....K......K....",
    "..KKKKKKKKKKKK..",
    "..KMMMMMMMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMMKMMMMK..",
    "..KDDDDDDDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "................",
  ],
  heart: [
    "................",
    "................",
    "..KKK....KKK....",
    ".KMMMK..KMMMK...",
    "KMWMMMKKMMMMMK..",
    "KMWMMMMMMMMMMK..",
    "KMMMMMMMMMMMMK..",
    ".KMMMMMMMMMMK...",
    "..KMMMMMMMMK....",
    "...KMMMMMMK.....",
    "....KMMMMK......",
    ".....KMMK.......",
    "......KK........",
    "................",
    "................",
    "................",
  ],
  flame: [
    "................",
    "......K.........",
    ".....KMK........",
    ".....KMMK.......",
    "....KMMMK..K....",
    "...KMMMMMKKMK...",
    "...KMMLMMMMMK...",
    "..KMMLLMMMMMMK..",
    "..KMMLLLMMMMMK..",
    "..KMLLWLLMMMMK..",
    "..KMLWWWLLMMMK..",
    "...KMLWWLLMMK...",
    "....KKKKKKKK....",
    "................",
    "................",
    "................",
  ],
  check: [
    "................",
    "................",
    "................",
    "............KK..",
    "...........KMMK.",
    "..........KMMK..",
    "..KK.....KMMK...",
    ".KMMK...KMMK....",
    "..KMMK.KMMK.....",
    "...KMMKMMK......",
    "....KMMMK.......",
    ".....KMK........",
    "......K.........",
    "................",
    "................",
    "................",
  ],
  // ikony 10 × 10, C = barva textu (currentColor)
  "i-home": [
    ".....CC.....",
    "....CCCC....",
    "...CCCCCC...",
    "..CCCCCCCC..",
    ".CCCCCCCCCC.",
    "CCCCCCCCCCCC",
    ".CCCCCCCCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
  ],
  "i-grid": [
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "............",
    "............",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
  ],
  "i-map": [
    "...CCCCCC...",
    "..CCCCCCCC..",
    ".CCCC..CCCC.",
    ".CCC....CCC.",
    ".CCC....CCC.",
    ".CCCC..CCCC.",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "....CCCC....",
    ".....CC.....",
    "............",
    "..CCCCCCCC..",
  ],
  "i-user": [
    "....CCCC....",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CCCCCC...",
    "....CCCC....",
    "............",
    "..CCCCCCCC..",
    ".CCCCCCCCCC.",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
  ],
  "i-plus": [
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
  ],
  "i-back": [
    ".....CC.....",
    "....CCC.....",
    "...CCC......",
    "..CCC.......",
    ".CCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    ".CCCCCCCCCCC",
    "..CCC.......",
    "...CCC......",
    "....CCC.....",
    ".....CC.....",
  ],
  "i-up": [
    "..........",
    "....CC....",
    "...CCCC...",
    "..CCCCCC..",
    ".CCC..CCC.",
    "CCC....CCC",
    "CC......CC",
    "..........",
    "..........",
    "..........",
  ],
  "i-down": [
    "..........",
    "..........",
    "..........",
    "CC......CC",
    "CCC....CCC",
    ".CCC..CCC.",
    "..CCCCCC..",
    "...CCCC...",
    "....CC....",
    "..........",
  ],
  "i-star": [
    "....CC....",
    "....CC....",
    "...CCCC...",
    "CCCCCCCCCC",
    ".CCCCCCCC.",
    "..CCCCCC..",
    "..CCCCCC..",
    ".CCC..CCC.",
    ".CC....CC.",
    "..........",
  ],
  "i-play": [
    "CC..........",
    "CCCC........",
    "CCCCCC......",
    "CCCCCCCC....",
    "CCCCCCCCCC..",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCC..",
    "CCCCCCCC....",
    "CCCCCC......",
    "CCCC........",
    "CC..........",
  ],
  sparkle: [
    "................",
    "................",
    ".......K........",
    ".......K........",
    "......KWK.......",
    "......KWK.......",
    "..KKKKWWWKKKK...",
    "......KWK.......",
    "......KWK.......",
    ".......K........",
    ".......K........",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
};

export interface SpriteColors {
  M: string;
  D: string;
  L: string;
}

const FIXED: Record<string, string> = { K: "#181425", W: "#FFFFFF", R: "#F6757A", C: "currentColor" };

export const spriteSize = (name: SpriteName) => ({ w: SPRITES[name][0].length, h: SPRITES[name].length });

/** Převede sprite na SVG obdélníky (souvislé pixely v řádku se spojí do jednoho). */
export function spriteRects(name: SpriteName, colors: SpriteColors) {
  const rects: { x: number; y: number; w: number; fill: string }[] = [];
  SPRITES[name].forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const c = row[x];
      if (c === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (row[x + w] === c) w++;
      const fill = FIXED[c] ?? colors[c as keyof SpriteColors];
      if (fill) rects.push({ x, y, w, fill });
      x += w;
    }
  });
  return rects;
}
