// Pixelové postavičky 16 × 16. Každý znak je jeden pixel:
// . průhledná, K obrys, W bílá (odlesk), M barva modulu, D stín, L světlo,
// R červená, P růžová, Y zlatá, A světle šedá, N tmavě šedá, C barva textu (ikony).
// Ikony modulů jsou předměty jako v inventáři RPG hry: obrys, čtyři tóny, světlo zleva nahoře.

import type { ModuleKey } from "./modules";

export type SpriteName =
  | ModuleKey | "star" | "trophy" | "crown" | "lock" | "heart" | "flame" | "check" | "sparkle"
  | "i-home" | "i-grid" | "i-map" | "i-user" | "i-plus" | "i-back" | "i-up" | "i-down" | "i-star" | "i-play" | "i-copy" | "i-share" | "i-edit" | "i-trash"
  | "w-sun" | "w-partly" | "w-cloud" | "w-rain" | "w-snow" | "w-storm" | "w-fog" | "w-moon";

export const SPRITES: Record<SpriteName, string[]> = {
  piva: [
    "................",
    "..KKKKKKKKK.....",
    ".KWWWWWWWWWK....",
    ".KWWWWAWWWWK....",
    ".KAWWWWWAWWK....",
    ".KMMWMMMWMMKKK..",
    ".KLMMMMMMMMKDDK.",
    ".KLMMMWMMMMK.DK.",
    ".KLMMMMMMWMK.DK.",
    ".KLMWMMMMMMK.DK.",
    ".KLMMMMMMMMKDDK.",
    ".KLMMMMMWMMKKK..",
    ".KDMMMMMMMDK....",
    ".KDDDDDDDDDK....",
    "..KKKKKKKKK.....",
    "................",
  ],
  meditace: [
    "................",
    ".......KK.......",
    "......KPPK......",
    "......KPWK......",
    "..KK.KPPPPK.KK..",
    ".KPPKKPPWPKKPPK.",
    ".KPWPKPPPPKPWPK.",
    "..KPPPKPPKPPPK..",
    "...KPPPKKPPPK...",
    "KK..KKPPPPKK..KK",
    "KMKKMMKKKKMMKKMK",
    ".KLMMMMMMMMMMMK.",
    "..KDDMMMMMMDDK..",
    "...KKKKKKKKKK...",
    "................",
    "................",
  ],
  hlaskomat: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KLLLMMMMMMMMMK.",
    "KLMMMMMMMMMMMMMK",
    "KLMWWMMMMWWMMMMK",
    "KMMWWMMMMWWMMMMK",
    "KMMMWMMMMMWMMMMK",
    "KMMWMMMMMWMMMMMK",
    "KMMMMMMMMMMMMMDK",
    ".KDMMMMMMMMMMDK.",
    "..KKKDDKKKKKKK..",
    "....KDK.........",
    "...KDK..........",
    "...KK...........",
    "................",
    "................",
  ],
  trenink: [
    "................",
    "................",
    "................",
    ".KKK........KKK.",
    "KLMMK......KLMMK",
    "KLMMKK....KKLMMK",
    "KLMMKKKKKKKKLMMK",
    "KLMMKAAAAAAKLMMK",
    "KLMMKNNNNNNKLMMK",
    "KLMMKKKKKKKKLMMK",
    "KLMMKK....KKLMMK",
    "KDDDK......KDDDK",
    ".KKK........KKK.",
    "................",
    "................",
    "................",
  ],
  lide: [
    "................",
    "....KK....KK....",
    "...KYYK..KYYK...",
    "...KYKYKKYKYK...",
    "....KKYYYYKK....",
    "..KKKKKYYKKKKK..",
    "..KLMMMYYMMMMK..",
    "..KDDDDYYDDDDK..",
    "..KKKKKYYKKKKK..",
    "...KLMMYYMMMK...",
    "...KLMMYYMMMK...",
    "...KMMMYYMMMK...",
    "...KDDDYYDDDK...",
    "...KKKKKKKKKK...",
    "................",
    "................",
  ],
  vdecnost: [
    "................",
    "...KKKKKKKKKK...",
    "..KDKLMMMMMMMK..",
    "..KDKMMMMMMMMK..",
    "..KDKMRRMRRMMK..",
    "..KDKMPRRRRMMK..",
    "..KDKMMRRRMMMK..",
    "..KDKMMMRMMMMK..",
    "..KDKMMMMMMMMK..",
    "..KDKMMMMMMMMK..",
    "..KDKMMMMMMMMK..",
    "..KDKDDDDDDDDK..",
    "..KKKWWWWWWWWK..",
    "...KKKKKKPKKKK..",
    ".........P......",
    "................",
  ],
  cornhole: [
    "................",
    "..KKKKKKKKKK....",
    "..KLLLLLLLLK....",
    "..KLMMKKMMMK....",
    "..KLMKKKKMMK....",
    "..KLMKKKKMMK....",
    "..KLMMKKMMMK....",
    "..KLMMMMMMMK....",
    "..KLMMMMMMMK....",
    "..KLMMMMMKKKKK..",
    "..KLMMMMKRPRRRK.",
    "..KLMMMMKRRRRRK.",
    "..KDDDDDKRRRRRK.",
    "..KKKKKKKRRRDRK.",
    ".........KKKKK..",
    "................",
  ],
  skore: [
    "................",
    "..KKKKKKKKKKK...",
    ".KLLLLLLLLLLLK..",
    ".KLMMMMMMMMMDK..",
    ".KLMKKMMMKKMDK..",
    ".KLMKKMMMKKMDK..",
    ".KLMMMMMMMMMDK..",
    ".KLMMMMKKMMMDK..",
    ".KLMMMMKKMMMDK..",
    ".KLMMMMMMMMMDK..",
    ".KLMKKMMMKKMDK..",
    ".KLMKKMMMKKMDK..",
    ".KLMMMMMMMMMDK..",
    ".KDDDDDDDDDDDK..",
    "..KKKKKKKKKKK...",
    "................",
  ],
  dech: [
    "................",
    ".......KK.......",
    ".......KK.......",
    "...KKK.KK.KKK...",
    "..KLLMKKKKMMMK..",
    ".KLMMMMKKMMMMMK.",
    ".KLMMMK.KK.KMMK.",
    ".KLMMMK....KMMK.",
    ".KLMMMMK..KMMMK.",
    ".KLMMMMK..KMMMK.",
    ".KMMMMDK..KDMMK.",
    ".KMMMDDK..KDDMK.",
    "..KDDDK....KDK..",
    "...KKK......K...",
    "................",
    "................",
  ],
  untrois: [
    "................",
    "................",
    "...KKK..KKKKKKK.",
    "..KLLK.KLLLLLLMK",
    ".KLMMK.KMKKKKMMK",
    ".KKMMK.KK...KMMK",
    "..KMMK...KKKKMK.",
    "..KMMK...KLLMMK.",
    "..KMMK...KKKKMMK",
    "..KMMK.KK...KMMK",
    ".KKMMKKKMKKKKMMK",
    ".KMMMMKKMMMMMMDK",
    ".KDDDDK.KDDDDDK.",
    ".KKKKKK..KKKKK..",
    "................",
    "................",
  ],
  odkazy: [
    "................",
    ".........KKKK...",
    "........KLMMMK..",
    ".......KLMKKMMK.",
    "......KLMK..KMK.",
    "......KMK..KMMK.",
    "....KKKMKKKMMK..",
    "...KLMKKMMMKK...",
    "..KLMKKMMMK.....",
    ".KLMK..KMK......",
    ".KMK..KMMK......",
    ".KMKKKMMK.......",
    "..KMMMMK........",
    "...KKKK.........",
    "................",
    "................",
  ],
  mista: [
    "................",
    ".....KKKKKK.....",
    "....KLLMMMMK....",
    "...KLMMMMMMMK...",
    "...KLMMKKMMMK...",
    "...KMMKWWKMMK...",
    "...KMMKWWKMMK...",
    "...KMMMKKMMMK...",
    "...KDMMMMMMDK...",
    "....KDMMMMDK....",
    ".....KDMMDK.....",
    "......KDDK......",
    ".......KK.......",
    ".....NNNNNN.....",
    "................",
    "................",
  ],
  filmy: [
    "................",
    "................",
    ".KKKKKKKKKKKKKK.",
    ".KWKKWWKKWWKKWK.",
    ".KKWWKKWWKKWWKK.",
    ".KKKKKKKKKKKKKK.",
    ".KLMMMMMMMMMMMK.",
    ".KLMMMMMMMMMMMK.",
    ".KMMWWWWWWMMMMK.",
    ".KMMMMMMMMMMMMK.",
    ".KMMWWWWMMMMMMK.",
    ".KDDDDDDDDDDDDK.",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
    "................",
  ],
  wishlist: [
    "................",
    "................",
    "....KKKKKKKK....",
    "...KWLLMMMMDK...",
    "..KWLLMMMMMMDK..",
    ".KKKKKKKKKKKKKK.",
    ".KLWMMMMMMMMMDK.",
    "..KLWMMMMMMMDK..",
    "...KLWMMMMMDK...",
    "....KLMMMMDK....",
    ".....KLMMDK.....",
    "......KMDK......",
    ".......KK.......",
    "................",
    "................",
    "................",
  ],
  finance: [
    "................",
    ".....KKKKKK.....",
    "...KKLLLLMMKK...",
    "..KLLMMMMMMMDK..",
    ".KLMMKKKKKKMMDK.",
    ".KLMKMMMMMMKMDK.",
    ".KLMKMLLMMMKMDK.",
    ".KMMKMMMMMMKMDK.",
    ".KMMKMMMMMDKMDK.",
    ".KMMKMMMMDDKMDK.",
    ".KMMMKKKKKKMDDK.",
    "..KMMMMMMMMDDK..",
    "...KKDDDDDDKK...",
    ".....KKKKKK.....",
    "................",
    "................",
  ],
  star: [
    ".......KK.......",
    "......KLMK......",
    "......KLMK......",
    ".....KLMMMK.....",
    "KKKKKKLMMMKKKKKK",
    "KLLLLLLMMMMMMMDK",
    ".KLMMMMMMMMMMDK.",
    "..KMMMMMMMMMDK..",
    "...KMMMMMMMDK...",
    "...KMMMMMMMDK...",
    "..KMMMMKKMMMDK..",
    "..KMMMK..KMMDK..",
    ".KMMDK....KMDDK.",
    ".KKKK......KKKK.",
    "................",
    "................",
  ],
  trophy: [
    "................",
    "...KKKKKKKKKK...",
    ".KKKMMMMMMLMKKK.",
    "KM.KMMMMMMLMK.MK",
    "KM.KMMMMMMMMK.MK",
    ".KKKMMMMMMMMKKK.",
    "...KMMMMMMMMK...",
    "....KMMMMMMK....",
    ".....KKMMKK.....",
    "......KMMK......",
    "......KMMK......",
    "....KKKKKKKK....",
    "....KDDDDDDK....",
    "....KKKKKKKK....",
    "................",
    "................",
  ],
  crown: [
    "................",
    "................",
    "................",
    "..K....K....K...",
    ".KMK..KMK..KMK..",
    ".KMMK.KMK.KMMK..",
    ".KMMMKMMMKMMMK..",
    ".KMMMMMMMMMMMK..",
    ".KMRMMMRMMMRMK..",
    ".KMMMMMMMMMMMK..",
    ".KKKKKKKKKKKKK..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  lock: [
    "................",
    "................",
    ".....KKKKKK.....",
    "....KK....KK....",
    "....K......K....",
    "....K......K....",
    "..KKKKKKKKKKKK..",
    "..KMMMMMMMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMMKMMMMK..",
    "..KDDDDDDDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "................",
  ],
  heart: [
    "................",
    "................",
    "..KKK....KKK....",
    ".KMMMK..KMMMK...",
    "KMWMMMKKMMMMMK..",
    "KMWMMMMMMMMMMK..",
    "KMMMMMMMMMMMMK..",
    ".KMMMMMMMMMMK...",
    "..KMMMMMMMMK....",
    "...KMMMMMMK.....",
    "....KMMMMK......",
    ".....KMMK.......",
    "......KK........",
    "................",
    "................",
    "................",
  ],
  flame: [
    "................",
    "......K.........",
    ".....KMK........",
    ".....KMMK.......",
    "....KMMMK..K....",
    "...KMMMMMKKMK...",
    "...KMMLMMMMMK...",
    "..KMMLLMMMMMMK..",
    "..KMMLLLMMMMMK..",
    "..KMLLWLLMMMMK..",
    "..KMLWWWLLMMMK..",
    "...KMLWWLLMMK...",
    "....KKKKKKKK....",
    "................",
    "................",
    "................",
  ],
  check: [
    "................",
    "................",
    "................",
    "............KK..",
    "...........KMMK.",
    "..........KMMK..",
    "..KK.....KMMK...",
    ".KMMK...KMMK....",
    "..KMMK.KMMK.....",
    "...KMMKMMK......",
    "....KMMMK.......",
    ".....KMK........",
    "......K.........",
    "................",
    "................",
    "................",
  ],
  // ikony 10 × 10, C = barva textu (currentColor)
  "i-home": [
    ".....CC.....",
    "....CCCC....",
    "...CCCCCC...",
    "..CCCCCCCC..",
    ".CCCCCCCCCC.",
    "CCCCCCCCCCCC",
    ".CCCCCCCCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
    ".CCCC..CCCC.",
  ],
  "i-grid": [
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "............",
    "............",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
    "CCCCC..CCCCC",
  ],
  "i-map": [
    "...CCCCCC...",
    "..CCCCCCCC..",
    ".CCCC..CCCC.",
    ".CCC....CCC.",
    ".CCC....CCC.",
    ".CCCC..CCCC.",
    "..CCCCCCCC..",
    "...CCCCCC...",
    "....CCCC....",
    ".....CC.....",
    "............",
    "..CCCCCCCC..",
  ],
  "i-user": [
    "....CCCC....",
    "...CCCCCC...",
    "...CCCCCC...",
    "...CCCCCC...",
    "....CCCC....",
    "............",
    "..CCCCCCCC..",
    ".CCCCCCCCCC.",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
  ],
  "i-plus": [
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
    "....CCCC....",
  ],
  "i-back": [
    ".....CC.....",
    "....CCC.....",
    "...CCC......",
    "..CCC.......",
    ".CCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    ".CCCCCCCCCCC",
    "..CCC.......",
    "...CCC......",
    "....CCC.....",
    ".....CC.....",
  ],
  "i-up": [
    "..........",
    "....CC....",
    "...CCCC...",
    "..CCCCCC..",
    ".CCC..CCC.",
    "CCC....CCC",
    "CC......CC",
    "..........",
    "..........",
    "..........",
  ],
  "i-down": [
    "..........",
    "..........",
    "..........",
    "CC......CC",
    "CCC....CCC",
    ".CCC..CCC.",
    "..CCCCCC..",
    "...CCCC...",
    "....CC....",
    "..........",
  ],
  "i-star": [
    "....CC....",
    "....CC....",
    "...CCCC...",
    "CCCCCCCCCC",
    ".CCCCCCCC.",
    "..CCCCCC..",
    "..CCCCCC..",
    ".CCC..CCC.",
    ".CC....CC.",
    "..........",
  ],
  "i-copy": [
    "..........",
    "...CCCCCCC",
    "...C.....C",
    "CCCCCCC..C",
    "C.....C..C",
    "C.....C..C",
    "C.....CCCC",
    "C.....C...",
    "C.....C...",
    "CCCCCCC...",
  ],
  "i-share": [
    "....CC....",
    "...CCCC...",
    "..CCCCCC..",
    "....CC....",
    "....CC....",
    "CC..CC..CC",
    "CC..CC..CC",
    "CC......CC",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
  ],
  "i-edit": [
    "........CC",
    ".......CCC",
    "......CCC.",
    ".....CCC..",
    "....CCC...",
    "...CCC....",
    "..CCC.....",
    ".CCC......",
    "CCC.......",
    "CCCC......",
  ],
  "i-trash": [
    "...CCCC...",
    "CCCCCCCCCC",
    "..........",
    ".CCCCCCCC.",
    ".C.C..C.C.",
    ".C.C..C.C.",
    ".C.C..C.C.",
    ".C.C..C.C.",
    ".C......C.",
    ".CCCCCCCC.",
  ],
  "w-sun": [
    "....YY....",
    ".Y..YY..Y.",
    "..YYYYYY..",
    "..YYYYYY..",
    "YYYYYYYYYY",
    "YYYYYYYYYY",
    "..YYYYYY..",
    "..YYYYYY..",
    ".Y..YY..Y.",
    "....YY....",
  ],
  "w-moon": [
    "...YYYY...",
    "..YYY.....",
    ".YYY......",
    ".YYY......",
    "YYYY......",
    "YYYY......",
    ".YYYY.....",
    ".YYYYY..Y.",
    "..YYYYYYY.",
    "...YYYYY..",
  ],
  "w-partly": [
    ".Y..Y.....",
    "..YYYY....",
    "YYYYYYY...",
    "..YYAAAA..",
    ".YYAWWWWA.",
    "..AWWWWWWA",
    ".AWWWWWWWA",
    "AWWWWWWWWA",
    "AAAAAAAAAA",
    "..........",
  ],
  "w-cloud": [
    "..........",
    "....AAA...",
    "...AWWWA..",
    "..AWWWWWA.",
    ".AAWWWWWWA",
    "AWWWWWWWWA",
    "AWWWWWWWWA",
    "AAAAAAAAAA",
    "..........",
    "..........",
  ],
  "w-rain": [
    "....AAA...",
    "...AWWWA..",
    ".AAWWWWWA.",
    "AWWWWWWWWA",
    "AAAAAAAAAA",
    "..........",
    ".B..B..B..",
    "B..B..B...",
    ".B..B..B..",
    "B..B..B...",
  ],
  "w-snow": [
    "....AAA...",
    "...AWWWA..",
    ".AAWWWWWA.",
    "AWWWWWWWWA",
    "AAAAAAAAAA",
    "..........",
    ".W...W..W.",
    "WWW.WWW...",
    ".W...W..W.",
    "...W...WWW",
  ],
  "w-storm": [
    "....NNN...",
    "...NAAAN..",
    ".NNAAAAAN.",
    "NAAAAAAAAN",
    "NNNNYYNNNN",
    "....YY....",
    "...YY.....",
    "..YYYYY...",
    "....YY....",
    "...YY.....",
  ],
  "w-fog": [
    "..........",
    "AAAAAAA...",
    "..........",
    "..AAAAAAAA",
    "..........",
    "AAAAAAAAA.",
    "..........",
    ".AAAAAAAAA",
    "..........",
    "AAAAAA....",
  ],
  "i-play": [
    "CC..........",
    "CCCC........",
    "CCCCCC......",
    "CCCCCCCC....",
    "CCCCCCCCCC..",
    "CCCCCCCCCCCC",
    "CCCCCCCCCCCC",
    "CCCCCCCCCC..",
    "CCCCCCCC....",
    "CCCCCC......",
    "CCCC........",
    "CC..........",
  ],
  sparkle: [
    "................",
    "................",
    ".......K........",
    ".......K........",
    "......KWK.......",
    "......KWK.......",
    "..KKKKWWWKKKK...",
    "......KWK.......",
    "......KWK.......",
    ".......K........",
    ".......K........",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
};

export interface SpriteColors {
  M: string;
  D: string;
  L: string;
}

const FIXED: Record<string, string> = {
  K: "#181425", W: "#FFFFFF", R: "#E43B44", P: "#F6757A", Y: "#FEE761", A: "#C0CBDC", N: "#5A6988", B: "#2CE8F5", C: "currentColor",
};

export const spriteSize = (name: SpriteName) => ({ w: SPRITES[name][0].length, h: SPRITES[name].length });

/** Převede sprite na SVG obdélníky (souvislé pixely v řádku se spojí do jednoho). */
export function spriteRects(name: SpriteName, colors: SpriteColors) {
  const rects: { x: number; y: number; w: number; fill: string }[] = [];
  SPRITES[name].forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const c = row[x];
      if (c === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (row[x + w] === c) w++;
      const fill = FIXED[c] ?? colors[c as keyof SpriteColors];
      if (fill) rects.push({ x, y, w, fill });
      x += w;
    }
  });
  return rects;
}
