// Pixelové postavičky 16 × 16. Každý znak je jeden pixel:
// . průhledná, K černá (obrys), W bílá, M barva modulu, D tmavší odstín, L světlejší odstín, R červená.

import type { ModuleKey } from "./modules";

export type SpriteName =
  | ModuleKey | "star" | "trophy" | "crown" | "lock" | "heart" | "flame" | "check" | "sparkle"
  | "i-home" | "i-grid" | "i-map" | "i-user" | "i-plus" | "i-back" | "i-up" | "i-down" | "i-star" | "i-play";

export const SPRITES: Record<SpriteName, string[]> = {
  piva: [
    "................",
    "..KKK..KKK......",
    ".KWWWKKWWWK.....",
    "KWWWWWWWWWWK....",
    "KWWWWWWWWWWK....",
    ".KWKWWWKWWKKKK..",
    ".KMWMMMMWMKDDMK.",
    ".KMMMMMMMMKKKDMK",
    ".KMKKMMMKKK..KMK",
    ".KMKKMMMKKK..KMK",
    ".KMMMMMMMMKKKDMK",
    ".KMLKMMMKLKDDMK.",
    ".KMMMKKKMMKKKK..",
    ".KDMMMMMMDK.....",
    ".KKKKKKKKKK.....",
    "................",
  ],
  meditace: [
    "................",
    ".....KKKKKK.....",
    "....KMMMMMMK....",
    "...KMMMMMMMMK...",
    "...KMKKMMKKMK...",
    "...KLMMMMMMLK...",
    "...KMMMKKMMMK...",
    "....KMMMMMMK....",
    "..KKKKMMMMKKKK..",
    ".KMMMMMMMMMMMMK.",
    ".KMKMMMMMMMMKMK.",
    "KMMMMMMMMMMMMMMK",
    "KDDDDDDDDDDDDDDK",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
  ],
  hlaskomat: [
    "................",
    "..KKKKKKKKKKKK..",
    ".KMMMMMMMMMMMMK.",
    "KMMMMMMMMMMMMMMK",
    "KMMKKMMMMMMKKMMK",
    "KMMKKMMMMMMKKMMK",
    "KMLMMMMMMMMMMLMK",
    "KMMMMKKKKKKMMMMK",
    "KMMMMKRRRRKMMMMK",
    "KMMMMMKKKKMMMMMK",
    ".KMMMMMMMMMMMMK.",
    "..KKKMMKKKKKKK..",
    "....KMK.........",
    "...KMK..........",
    "...KK...........",
    "................",
  ],
  trenink: [
    "................",
    "................",
    "................",
    ".KKK........KKK.",
    "KMMMK......KMMMK",
    "KMMMKK....KKMMMK",
    "KMMMKWKKKKWKMMMK",
    "KMMMKWWWWWWKMMMK",
    "KMMMKKKKKKKKMMMK",
    "KMMMKK....KKMMMK",
    "KDDDK......KDDDK",
    ".KKK........KKK.",
    "................",
    "................",
    "................",
    "................",
  ],
  lide: [
    "................",
    "...KKK....KKK...",
    "..KWWWK..KWWWK..",
    "..KWKWWKKWWKWK..",
    "...KKKWKKWKKK...",
    ".KKKKKKKKKKKKKK.",
    ".KMMMMMKKMMMMMK.",
    ".KMMMMMKKMMMMMK.",
    ".KKKKKKKKKKKKKK.",
    "..KMMMMKKMMMMK..",
    "..KMLMMKKMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KDDDDKKDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
  ],
  denik: [
    "................",
    "..KKKKKKKKKKKK..",
    "..KKMMMMMMWWMK..",
    "..KKMMMMMMWWMK..",
    "..KKMMMMMMWWMK..",
    "..KKMMMMMMKWMK..",
    "..KKMKKKKKKMMK..",
    "..KKMMMMMMMMMK..",
    "..KKMKKKKKKKMK..",
    "..KKMMMMMMMMMK..",
    "..KKMKKKKMMMMK..",
    "..KKMMMMMMMMMK..",
    "..KKDDDDDDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
  ],
  odkazy: [
    "................",
    ".........KKKKKK.",
    ".........KMMMMK.",
    "..........KMMMK.",
    ".KKKKKK..KMMMMK.",
    ".KWWWWK.KMMKMMK.",
    ".KWWWWKKMMK.KK..",
    ".KWWWKKMMK......",
    ".KWWKKMMK..KK...",
    ".KWWKMMK..KWK...",
    ".KWWWKK..KWWK...",
    ".KWWWWWWWWWWK...",
    ".KDDDDDDDDDDK...",
    ".KKKKKKKKKKKK...",
    "................",
    "................",
  ],
  mista: [
    "................",
    ".....KKKKKK.....",
    "....KMMMMMMK....",
    "...KMLMMMMMMK...",
    "...KMMKKKKMMK...",
    "...KMMKWWKMMK...",
    "...KMMKWWKMMK...",
    "...KMMKKKKMMK...",
    "...KMMMMMMMMK...",
    "....KMMMMMMK....",
    ".....KMMMMK.....",
    "......KMMK......",
    ".......KK.......",
    "....KKKKKKKK....",
    "................",
    "................",
  ],
  filmy: [
    "................",
    "................",
    ".KKKKKKKKKKKKKK.",
    ".KWKKWWKKWWKKWK.",
    ".KKKKKKKKKKKKKK.",
    ".KMMMMMMMMMMMMK.",
    ".KMLMMMMMMMMMMK.",
    ".KMMKKKKKKKKMMK.",
    ".KMMMMMMMMMMMMK.",
    ".KMMKKKKKKMMMMK.",
    ".KMMMMMMMMMMMMK.",
    ".KDDDDDDDDDDDDK.",
    ".KKKKKKKKKKKKKK.",
    "................",
    "................",
    "................",
  ],
  wishlist: [
    "................",
    "................",
    "....KKKKKKKK....",
    "...KWWMMMMDDK...",
    "..KWWMMMMMMDDK..",
    ".KKKKKKKKKKKKKK.",
    ".KWMMMMMMMMMMDK.",
    "..KWMMMMMMMMDK..",
    "...KWMMMMMMDK...",
    "....KWMMMMDK....",
    ".....KMMMMK.....",
    "......KMMK......",
    ".......KK.......",
    "................",
    "................",
    "................",
  ],
  finance: [
    "................",
    "................",
    ".....KKKKKK.....",
    "...KKMMMMMMKK...",
    "..KMMWWMMMMMMK..",
    ".KMMWMMKKKMMMMK.",
    ".KMWMMKMMMKMMDK.",
    ".KMMMMKMMMMMMDK.",
    ".KMMMMKMMMKMMDK.",
    ".KMMMMMKKKMMMDK.",
    "..KMMMMMMMMMDK..",
    "...KKDDDDDDKK...",
    ".....KKKKKK.....",
    "................",
    "................",
    "................",
  ],
  star: [
    ".......K........",
    "......KMK.......",
    "......KMK.......",
    ".....KMMMK......",
    "KKKKKKMMMKKKKKK.",
    ".KMMMMMMMMMMMK..",
    "..KMMMMMMMMMK...",
    "...KMMMMMMMK....",
    "...KMMMMMMMK....",
    "..KMMMMKMMMMK...",
    "..KMMMK.KMMMK...",
    ".KMMK.....KMMK..",
    ".KKK.......KKK..",
    "................",
    "................",
    "................",
  ],
  trophy: [
    "................",
    "...KKKKKKKKKK...",
    ".KKKMMMMMMLMKKK.",
    "KM.KMMMMMMLMK.MK",
    "KM.KMMMMMMMMK.MK",
    ".KKKMMMMMMMMKKK.",
    "...KMMMMMMMMK...",
    "....KMMMMMMK....",
    ".....KKMMKK.....",
    "......KMMK......",
    "......KMMK......",
    "....KKKKKKKK....",
    "....KDDDDDDK....",
    "....KKKKKKKK....",
    "................",
    "................",
  ],
  crown: [
    "................",
    "................",
    "................",
    "..K....K....K...",
    ".KMK..KMK..KMK..",
    ".KMMK.KMK.KMMK..",
    ".KMMMKMMMKMMMK..",
    ".KMMMMMMMMMMMK..",
    ".KMRMMMRMMMRMK..",
    ".KMMMMMMMMMMMK..",
    ".KKKKKKKKKKKKK..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  lock: [
    "................",
    "................",
    ".....KKKKKK.....",
    "....KK....KK....",
    "....K......K....",
    "....K......K....",
    "..KKKKKKKKKKKK..",
    "..KMMMMMMMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMKKMMMMK..",
    "..KMMMMMKMMMMK..",
    "..KDDDDDDDDDDK..",
    "..KKKKKKKKKKKK..",
    "................",
    "................",
    "................",
  ],
  heart: [
    "................",
    "................",
    "..KKK....KKK....",
    ".KMMMK..KMMMK...",
    "KMWMMMKKMMMMMK..",
    "KMWMMMMMMMMMMK..",
    "KMMMMMMMMMMMMK..",
    ".KMMMMMMMMMMK...",
    "..KMMMMMMMMK....",
    "...KMMMMMMK.....",
    "....KMMMMK......",
    ".....KMMK.......",
    "......KK........",
    "................",
    "................",
    "................",
  ],
  flame: [
    "................",
    "......K.........",
    ".....KMK........",
    ".....KMMK.......",
    "....KMMMK..K....",
    "...KMMMMMKKMK...",
    "...KMMLMMMMMK...",
    "..KMMLLMMMMMMK..",
    "..KMMLLLMMMMMK..",
    "..KMLLWLLMMMMK..",
    "..KMLWWWLLMMMK..",
    "...KMLWWLLMMK...",
    "....KKKKKKKK....",
    "................",
    "................",
    "................",
  ],
  check: [
    "................",
    "................",
    "................",
    "............KK..",
    "...........KMMK.",
    "..........KMMK..",
    "..KK.....KMMK...",
    ".KMMK...KMMK....",
    "..KMMK.KMMK.....",
    "...KMMKMMK......",
    "....KMMMK.......",
    ".....KMK........",
    "......K.........",
    "................",
    "................",
    "................",
  ],
  // ikony 10 × 10, C = barva textu (currentColor)
  "i-home": [
    "....CC....",
    "...CCCC...",
    "..CCCCCC..",
    ".CCCCCCCC.",
    "CCCCCCCCCC",
    ".CC....CC.",
    ".CC.CC.CC.",
    ".CC.CC.CC.",
    ".CC.CC.CC.",
    ".CCCCCCCC.",
  ],
  "i-grid": [
    "CCCC..CCCC",
    "C..C..C..C",
    "C..C..C..C",
    "CCCC..CCCC",
    "..........",
    "..........",
    "CCCC..CCCC",
    "C..C..C..C",
    "C..C..C..C",
    "CCCC..CCCC",
  ],
  "i-map": [
    "..CCCCCC..",
    ".CC....CC.",
    "CC..CC..CC",
    "CC.CCCC.CC",
    "CC..CC..CC",
    ".CC....CC.",
    "..CC..CC..",
    "...CCCC...",
    "....CC....",
    "..........",
  ],
  "i-user": [
    "...CCCC...",
    "..CC..CC..",
    "..CC..CC..",
    "..CC..CC..",
    "...CCCC...",
    "..........",
    ".CCCCCCCC.",
    "CC......CC",
    "CC......CC",
    "CCCCCCCCCC",
  ],
  "i-plus": [
    "...CCCC...",
    "...CCCC...",
    "...CCCC...",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
    "...CCCC...",
    "...CCCC...",
    "...CCCC...",
  ],
  "i-back": [
    "....CC....",
    "...CC.....",
    "..CC......",
    ".CC.......",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
    ".CC.......",
    "..CC......",
    "...CC.....",
    "....CC....",
  ],
  "i-up": [
    "..........",
    "....CC....",
    "...CCCC...",
    "..CCCCCC..",
    ".CCC..CCC.",
    "CCC....CCC",
    "CC......CC",
    "..........",
    "..........",
    "..........",
  ],
  "i-down": [
    "..........",
    "..........",
    "..........",
    "CC......CC",
    "CCC....CCC",
    ".CCC..CCC.",
    "..CCCCCC..",
    "...CCCC...",
    "....CC....",
    "..........",
  ],
  "i-star": [
    "....CC....",
    "....CC....",
    "...CCCC...",
    "CCCCCCCCCC",
    ".CCCCCCCC.",
    "..CCCCCC..",
    "..CCCCCC..",
    ".CCC..CCC.",
    ".CC....CC.",
    "..........",
  ],
  "i-play": [
    "CC........",
    "CCCC......",
    "CCCCCC....",
    "CCCCCCCC..",
    "CCCCCCCCCC",
    "CCCCCCCCCC",
    "CCCCCCCC..",
    "CCCCCC....",
    "CCCC......",
    "CC........",
  ],
  sparkle: [
    "................",
    "................",
    ".......K........",
    ".......K........",
    "......KWK.......",
    "......KWK.......",
    "..KKKKWWWKKKK...",
    "......KWK.......",
    "......KWK.......",
    ".......K........",
    ".......K........",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
};

export interface SpriteColors {
  M: string;
  D: string;
  L: string;
}

const FIXED: Record<string, string> = { K: "#000000", W: "#FFFFFF", R: "#FF4D6D", C: "currentColor" };

export const spriteSize = (name: SpriteName) => ({ w: SPRITES[name][0].length, h: SPRITES[name].length });

/** Převede sprite na SVG obdélníky (souvislé pixely v řádku se spojí do jednoho). */
export function spriteRects(name: SpriteName, colors: SpriteColors) {
  const rects: { x: number; y: number; w: number; fill: string }[] = [];
  SPRITES[name].forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const c = row[x];
      if (c === ".") {
        x++;
        continue;
      }
      let w = 1;
      while (row[x + w] === c) w++;
      const fill = FIXED[c] ?? colors[c as keyof SpriteColors];
      if (fill) rects.push({ x, y, w, fill });
      x += w;
    }
  });
  return rects;
}
